### PR TITLE
small fixes

### LINKED ISSUE #14: Warning: Invalid DOM property `for`. Did you mean `htmlFor`?
```
index.js:1 Warning: Invalid DOM property `for`. Did you mean `htmlFor`?
    in label (at ProjectCard.js:28)
    in div (created by ForwardRef(CardContent))
    in ForwardRef(CardContent) (created by WithStyles(ForwardRef(CardContent)))
    in WithStyles(ForwardRef(CardContent)) (at ProjectCard.js:24)
    in div (created by ForwardRef(Paper))
    in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
    in WithStyles(ForwardRef(Paper)) (created by ForwardRef(Card))
    in ForwardRef(Card) (created by WithStyles(ForwardRef(Card)))
    in WithStyles(ForwardRef(Card)) (at ProjectCard.js:23)
    in ProjectCard (at App.js:16)
    in div (at App.js:13)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.js:12)
    in App (at src/index.js:9)
    in StrictMode (at src/index.js:8)
```

### PR DESCRIPTION
**Pull request by clarkngo**
This PR resolves #14 and #15

### CODE REVIEW

File: client/src/Components/ProjectCard.js [hunk 1]
```diff
@@ -29,7 +29,7 @@ export default function ProjectCard() {
                 <CardActions>
                     <Button variant="outlined">VIEW PROJECT</Button>
                 </CardActions>
-            </CardContent>
+            </CardContent>Z
```
Comment (t0ri) [inline client/src/Components/ProjectCard.js:32]: Looks like a typo here?

Comment (clarkngo) [reply client/src/Components/ProjectCard.js:32]: Yes. a typo =)
